// @generated by jit/build.rs. DO NOT EDIT.
pub(crate) static ALIAS_RULES: &[AliasRule] = &[
    AliasRule {
        alias: "bfc",
        canonical: "bfm",
        canonical_id: 77,
        transform: AliasTransform::BitfieldBfc,
    },
    AliasRule {
        alias: "bfi",
        canonical: "bfm",
        canonical_id: 77,
        transform: AliasTransform::BitfieldBfi,
    },
    AliasRule {
        alias: "bfxil",
        canonical: "bfm",
        canonical_id: 77,
        transform: AliasTransform::BitfieldBfxil,
    },
    AliasRule {
        alias: "cinc",
        canonical: "csinc",
        canonical_id: 325,
        transform: AliasTransform::CincLike,
    },
    AliasRule {
        alias: "cmn",
        canonical: "adds",
        canonical_id: 16,
        transform: AliasTransform::CmnLike,
    },
    AliasRule {
        alias: "cmp",
        canonical: "subs",
        canonical_id: 1317,
        transform: AliasTransform::CmpLike,
    },
    AliasRule {
        alias: "cneg",
        canonical: "csneg",
        canonical_id: 327,
        transform: AliasTransform::CnegLike,
    },
    AliasRule {
        alias: "cset",
        canonical: "csinc",
        canonical_id: 325,
        transform: AliasTransform::CsetLike,
    },
    AliasRule {
        alias: "csetm",
        canonical: "csinv",
        canonical_id: 326,
        transform: AliasTransform::CsetLike,
    },
    AliasRule {
        alias: "dc",
        canonical: "sys",
        canonical_id: 1355,
        transform: AliasTransform::DcLike,
    },
    AliasRule {
        alias: "fcvtl2",
        canonical: "fcvtl",
        canonical_id: 398,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "fcvtn2",
        canonical: "fcvtn",
        canonical_id: 402,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "ldswpal",
        canonical: "swpal",
        canonical_id: 1336,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "mov",
        canonical: "add",
        canonical_id: 5,
        transform: AliasTransform::MovLike,
    },
    AliasRule {
        alias: "mvn",
        canonical: "eon",
        canonical_id: 346,
        transform: AliasTransform::MvnLike,
    },
    AliasRule {
        alias: "pmull2",
        canonical: "pmull",
        canonical_id: 881,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "ret",
        canonical: "ret",
        canonical_id: 971,
        transform: AliasTransform::RetDefault,
    },
    AliasRule {
        alias: "sbfiz",
        canonical: "sbfm",
        canonical_id: 1019,
        transform: AliasTransform::BitfieldSbfiz,
    },
    AliasRule {
        alias: "sbfx",
        canonical: "sbfm",
        canonical_id: 1019,
        transform: AliasTransform::BitfieldSbfx,
    },
    AliasRule {
        alias: "shrn2",
        canonical: "shrn",
        canonical_id: 1085,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "smull2",
        canonical: "smull",
        canonical_id: 1127,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "sqxtn2",
        canonical: "sqxtn",
        canonical_id: 1186,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "sqxtun2",
        canonical: "sqxtun",
        canonical_id: 1189,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "sshll2",
        canonical: "sshll",
        canonical_id: 1199,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "stsetl",
        canonical: "ldsetl",
        canonical_id: 718,
        transform: AliasTransform::StsetlLike,
    },
    AliasRule {
        alias: "sxtl",
        canonical: "sshll",
        canonical_id: 1199,
        transform: AliasTransform::ExtendLongZero,
    },
    AliasRule {
        alias: "sxtl2",
        canonical: "sshll",
        canonical_id: 1199,
        transform: AliasTransform::ExtendLongZero,
    },
    AliasRule {
        alias: "tst",
        canonical: "ands",
        canonical_id: 33,
        transform: AliasTransform::TstLike,
    },
    AliasRule {
        alias: "uabdl2",
        canonical: "uabdl",
        canonical_id: 1376,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "ubfx",
        canonical: "ubfm",
        canonical_id: 1389,
        transform: AliasTransform::BitfieldUbfx,
    },
    AliasRule {
        alias: "umull2",
        canonical: "umull",
        canonical_id: 1425,
        transform: AliasTransform::PureRename,
    },
    AliasRule {
        alias: "uxtl",
        canonical: "ushll",
        canonical_id: 1466,
        transform: AliasTransform::ExtendLongZero,
    },
    AliasRule {
        alias: "uxtl2",
        canonical: "ushll",
        canonical_id: 1466,
        transform: AliasTransform::ExtendLongZero,
    },
];

pub(crate) fn lookup_alias_rule(mnemonic: &str) -> Option<&'static AliasRule> {
    let idx = ALIAS_RULES
        .binary_search_by(|rule| rule.alias.cmp(mnemonic))
        .ok()?;
    Some(&ALIAS_RULES[idx])
}

pub(crate) static CONDITIONAL_BRANCH_ALIAS_RULES: &[ConditionalBranchAliasRule] = &[
    ConditionalBranchAliasRule {
        alias: "b.al",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 14,
    },
    ConditionalBranchAliasRule {
        alias: "b.cc",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 3,
    },
    ConditionalBranchAliasRule {
        alias: "b.cs",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 2,
    },
    ConditionalBranchAliasRule {
        alias: "b.eq",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 0,
    },
    ConditionalBranchAliasRule {
        alias: "b.ge",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 10,
    },
    ConditionalBranchAliasRule {
        alias: "b.gt",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 12,
    },
    ConditionalBranchAliasRule {
        alias: "b.hi",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 8,
    },
    ConditionalBranchAliasRule {
        alias: "b.hs",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 2,
    },
    ConditionalBranchAliasRule {
        alias: "b.le",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 13,
    },
    ConditionalBranchAliasRule {
        alias: "b.lo",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 3,
    },
    ConditionalBranchAliasRule {
        alias: "b.ls",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 9,
    },
    ConditionalBranchAliasRule {
        alias: "b.lt",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 11,
    },
    ConditionalBranchAliasRule {
        alias: "b.mi",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 4,
    },
    ConditionalBranchAliasRule {
        alias: "b.ne",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 1,
    },
    ConditionalBranchAliasRule {
        alias: "b.nv",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 15,
    },
    ConditionalBranchAliasRule {
        alias: "b.pl",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 5,
    },
    ConditionalBranchAliasRule {
        alias: "b.vc",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 7,
    },
    ConditionalBranchAliasRule {
        alias: "b.vs",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 6,
    },
    ConditionalBranchAliasRule {
        alias: "bal",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 14,
    },
    ConditionalBranchAliasRule {
        alias: "bcc",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 3,
    },
    ConditionalBranchAliasRule {
        alias: "bcs",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 2,
    },
    ConditionalBranchAliasRule {
        alias: "beq",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 0,
    },
    ConditionalBranchAliasRule {
        alias: "bge",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 10,
    },
    ConditionalBranchAliasRule {
        alias: "bgt",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 12,
    },
    ConditionalBranchAliasRule {
        alias: "bhi",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 8,
    },
    ConditionalBranchAliasRule {
        alias: "bhs",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 2,
    },
    ConditionalBranchAliasRule {
        alias: "ble",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 13,
    },
    ConditionalBranchAliasRule {
        alias: "blo",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 3,
    },
    ConditionalBranchAliasRule {
        alias: "bls",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 9,
    },
    ConditionalBranchAliasRule {
        alias: "blt",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 11,
    },
    ConditionalBranchAliasRule {
        alias: "bmi",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 4,
    },
    ConditionalBranchAliasRule {
        alias: "bne",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 1,
    },
    ConditionalBranchAliasRule {
        alias: "bnv",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 15,
    },
    ConditionalBranchAliasRule {
        alias: "bpl",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 5,
    },
    ConditionalBranchAliasRule {
        alias: "bvc",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 7,
    },
    ConditionalBranchAliasRule {
        alias: "bvs",
        base_mnemonic: "b",
        base_mnemonic_id: 60,
        condition_code: 6,
    },
];

pub(crate) fn lookup_conditional_branch_alias(mnemonic: &str) -> Option<&'static ConditionalBranchAliasRule> {
    let idx = CONDITIONAL_BRANCH_ALIAS_RULES
        .binary_search_by(|rule| rule.alias.cmp(mnemonic))
        .ok()?;
    Some(&CONDITIONAL_BRANCH_ALIAS_RULES[idx])
}
